### ISSUE TITLE
Found non-deterministic tests.

### ISSUE THREAD

**Issue by harshith2000** [EliasStar/JsonRpc4J#7]
**Describe the bug**
The following tests fail due to an assertCheck between two JSON Strings.

1. [testOptionalSerialization()](https://github.com/EliasStar/JsonRpc4J/blob/6d7f58389e86efa4f44cc8906a7d1963b7f208b9/src/test/java/eliasstar/gson/OptionalTypeAdapterTests.java#L43)
2. [testNotificationSending()](https://github.com/EliasStar/JsonRpc4J/blob/6d7f58389e86efa4f44cc8906a7d1963b7f208b9/src/test/java/eliasstar/jsonrpc/ConnectionTests.java#L153)
3. [testNotificationSerialization()](https://github.com/EliasStar/JsonRpc4J/blob/6d7f58389e86efa4f44cc8906a7d1963b7f208b9/src/test/java/eliasstar/jsonrpc/objects/NotificationTests.java#L42)
4. [testRequestIdSerialization()](https://github.com/EliasStar/JsonRpc4J/blob/6d7f58389e86efa4f44cc8906a7d1963b7f208b9/src/test/java/eliasstar/jsonrpc/objects/RequestTests.java#L49)
5. [testRequestParamsSerialization()](https://github.com/EliasStar/JsonRpc4J/blob/6d7f58389e86efa4f44cc8906a7d1963b7f208b9/src/test/java/eliasstar/jsonrpc/objects/RequestTests.java#L73)

The primary issue in these functions was the reliance on the specific ordering of keys in the serialized JSON strings for comparisons in the test assertions. In JSON, the order of keys is not guaranteed and can vary depending on how the JSON serialization is implemented. This variability led to test failures, even though the JSON strings were structurally equivalent and contained the same data.

**Fix:**
The fix involved using Gson, a popular JSON processing library in Java, to parse the expected and actual JSON strings into JsonObject instances before comparing them. By doing so, the comparison became order-independent, focusing solely on the structure and content of the JSON data. This approach ensured that the tests were robust against differences in key ordering, thereby accurately validating the correctness of the JSON serialization logic regardless of the order in which the keys appeared in the serialized JSON strings. The fix was applied consistently across all functions, streamlining the test verification process and improving the reliability of the tests.

**How to reproduce**

**Steps to reproduce the behavior:**
I used an open-source tool called [NonDex](https://github.com/TestingResearchIllinois/NonDex) to detect the assumption by shuffling the order of returned exception types.
Running the following commands will test the aforementioned operation

**Clone the Repo**
```
https://github.com/EliasStar/JsonRpc4J.git
```
**Compile the project**
```
mvn install -am -DskipTests
```
**(Optional) Run the unit test**
```
mvn test
```
**Run the unit test using NonDex**
```
mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex
```

Stack trace for additional information:
```
[ERROR] Failures: 
[ERROR]   OptionalTypeAdapterTests.testOptionalSerialization:50 expected: <{"testString":null,"testOptional":"test"}> but was: <{"testOptional":"test","testString":null}>
[ERROR]   ConnectionTests.testNotificationSending:171 Multiple Failures (2 failures)
        org.opentest4j.AssertionFailedError: expected: <{"jsonrpc":"2.0","method":"test","params":[]}> but was: <{"params":[],"jsonrpc":"2.0","method":"test"}>
        org.opentest4j.AssertionFailedError: expected: <{"jsonrpc":"2.0","method":"test","params":{}}> but was: <{"params":{},"jsonrpc":"2.0","method":"test"}>
[ERROR]   NotificationTests.testNotificationSerialization:46 Multiple Failures (2 failures)
        org.opentest4j.AssertionFailedError: expected: <{"jsonrpc":"2.0","method":"test"}> but was: <{"method":"test","jsonrpc":"2.0"}>
        org.opentest4j.AssertionFailedError: expected: <{"jsonrpc":"2.0","method":"test"}> but was: <{"method":"test","jsonrpc":"2.0"}>
[ERROR]   RequestTests.testRequestIdSerialization:56->lambda$testRequestIdSerialization$2:56 Multiple Failures (2 failures)
        org.opentest4j.AssertionFailedError: expected: <{"jsonrpc":"2.0","id":"test","method":"test"}> but was: <{"jsonrpc":"2.0","method":"test","id":"test"}>
        org.opentest4j.AssertionFailedError: expected: <{"jsonrpc":"2.0","id":"test","method":"test"}> but was: <{"method":"test","id":"test","jsonrpc":"2.0"}>
[ERROR]   RequestTests.testRequestParamsSerialization:79 expected: <{"jsonrpc":"2.0","method":"test","params":["test",0,null]}> but was: <{"params":["test",0,null],"method":"test","jsonrpc":"2.0"}>

```

**Comment by EliasStar** [comment]
Thanks for your issue! I will be looking into it shortly.
